---
title: "Diferenças em diferenças"
subtitle: "Lista de Exercícios IV"
author: "Rafael Bressan"
date: "UDESC/Esag </br> `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Questão 1

Considere a configuração canônica do DID com T = 2 e N = 2.

$$y_{it} = \beta_0 + \beta_1 State_i + \beta_2 Post_t + \theta D_{it} + \varepsilon_{it}$$

suponha que a variável de tempo seja omitida. Assim, a equação de estimativa é

$$y_{it} = \beta_0 + \beta_1 State_i + \beta_2 Post_t + \varepsilon_{it}$$

onde $D_{it}= State_i \cdot Time_t$ é o indicador de tratamento.

(a) Encontre uma expressão algébrica para o estimador de mínimos quadrados $\hat\theta$.

(b) Mostre que $\hat\theta$ é função apenas da subamostra tratada e não da subamostra não tratada.

(c) $\hat\theta$ é um estimador de diferença-em-diferenças?

(d) Sob quais premissas $\hat\theta$ pode ser um estimador apropriado do efeito do tratamento?

## Questão 2

Condidere o modelo básico de efeito fixo em duas vias
$$y_{it} = \theta D_{it} + u_i + \delta_t + \varepsilon_{it}.$$

Em vez de assumir que $D_{it}$ e $\varepsilon_{it}$ são independentes, assuma que temos uma variável instrumental $z_{it}$ que é independente de $\varepsilon_{it}$ mas está correlacionada com $D_ {it}$. Descreva como estimar $\theta$.


## Questão 3

MOSTRAR NA PRÁTICA A EQUIVALENCIA ENTRE DID 2X2 E TWFE

## Questão 4

SIMULAR TRATAMENTO ESCALONADO E MOSTRAR COMO TWFE É VIESADO