---
title: "Modelos de Equações Simultâneas"
subtitle: "Lista de Exercícios III"
author: "Rafael Bressan"
date: "UDESC/Esag </br> `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Questão 1

São corretas as afirmativas. Em modelos de equações simultâneas:

- ($\phantom{X}$) o problema da identificação precede o da estimação.

- ($\phantom{X}$) os estimadores de mínimos quadrados indiretos e os de mínimos quadrados de dois estágios são não-tendenciosos e consistentes.

- ($\phantom{X}$) se uma equação é exatamente identificada, os métodos de mínimos quadrados indiretos e de dois estágios produzem resultados idênticos.

- ($\phantom{X}$) o método de mínimos quadrados indiretos pode ser aplicado tanto a equações exatamente identificados quanto a equações sobreidentificadas.

## Questão 2

Considere o seguinte modelo de equações simultâneas:

Equação de Demanda: $Q_t = \alpha_0 + \alpha_1 P_t + \alpha_2 R_t + u_{1t}$
Equação de oferta: $Q_t = \beta_0 + \beta_1 P_t + \beta_2 P_{t-1} + u_{2t}$

em que no período $t$, $Q_t$ é a quantidade de produto, $P_t$, o preço (endógeno) do produto, $R_t$  a renda do consumidor e os erros idiossincráticos são $u_{1t}\perp u_{2t}$. A partir destas equações são obtidas as equações na forma reduzida: $P_t = \pi_0 + \pi_1 R_t + \pi_2 P_{t-1} + v_t$ e $Q_t = \pi_3 + \pi_4 R_t + \pi_5 P_{t-1} +w_t$.

São corretas as afirmativas

- ($\phantom{X}$) Assim sendo, $\pi_0=\frac{\beta_0-\alpha_0}{\alpha_1-\beta_1}$, $\pi_1=\frac{\alpha_2}{\alpha_1-\beta_1}$ e $\pi_2=\frac{\beta_2}{\alpha_1-\beta_1}$

- ($\phantom{X}$) A condição de ordem sugere que a primeira e a segunda equações são identificadas

- ($\phantom{X}$) Se multiplicarmos a equação de demanda por $\lambda (0 < \lambda < 1)$ e a equação de oferta por $(1- \lambda)$ e somá-las, desde que o resultado dessa soma seja diferente da equação de oferta e da equação de demanda, as duas serão identificadas.

- ($\phantom{X}$) O método de mínimos quadrados ordinários produz estimadores consistentes e eficientes dos parâmetros da forma estrutural.

- ($\phantom{X}$) Para verificar se qualquer equação do sistema é identificável, basta aplicar a condição de ordem.

